# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet publish BlogApi --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet build $(buildConfiguration) + publish'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: PublishBuildArtifacts@1

# steps:
# - script: |
#     dotnet build --configuration $(buildConfiguration)
#     dotnet test BlogApi.Tests --configuration $(buildConfiguration) --logger trx
#     dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
    
# - task: PublishTestResults@2
#   condition: succeededOrFailed()
#   inputs:
#     testRunner: xUnit
#     testResultsFiles: '**/*.xml'

# - task: PublishBuildArtifacts@1
